version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tpcdata"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yetamk8xfeqr"
s3_prefix = "tpcdata"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
